version: '3.4'

services:
  sql-server:
    image: microsoft/mssql-server-windows-express:latest
    ports:
      - "1433:1433"
  xbit-api:
    image: xbitapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:80"
    depends_on:
      - sql-server