version: '3.5'

services:
  sql_server:
    image: microsoft/mssql-server-windows-express:latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
  xbit-api:
    container_name: xbitapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "52706:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sql_server

networks:
  default:
    external:
      name: nat
